docker: Don't install python3-virtualenv
It clashes with python3.x-venv packages and results in the following
error:

ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'